version: '3'
services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: webshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - postgres_network

  app:
    image: shop-app:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/webshop
      SPRING_DATASOURCE_LOGIN: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - postgres_network
    depends_on:
      - postgres

networks:
  postgres_network: