version: '3'
services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: webshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./simple_shop/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - service_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - service_network

  simple_shop:
    image: shop-app:latest
    build:
      context: .
      dockerfile: simple_shop/docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/webshop
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: admin
      SPRING_DATA_REDIS_HOST: redis
      PAYMENT_APP_HOST: payment_service
    networks:
      - service_network
    depends_on:
      - postgres
      - redis

  payment_service:
    image: payment_service-app:latest
    build:
      context: .
      dockerfile: payment_service/docker/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - service_network
#    depends_on:
#      - simple_shop

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: start-dev --import-realm
    networks:
      - service_network

networks:
  service_network: